version: '2'

services: 
    flask:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .flaskenv
        image: flask
        network_mode: host
        ports:
            - '5000:5000'
        volumes:
            - '.:/app'